---
- name: Create Free Tier EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: ansibleOS # Nome da chave criada na console da AWS
    region: us-east-1
    instance_type: t2.micro
    image:
      id: ami-0557a15b87f6559cf
    template_file: template.j2
    dest_file: /var/www/html/index.html
    host_name: "{{ ansible_host }}"
  tasks:
  - name: 'Criar segurança de grupo'
    ec2_group:
      name: my-security-group
      description: Allow SSH and HTTP access
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
    register: ec2_group

  - name: 'Lançar instancia'
    ec2_instance:
      name: "EC2_TESTE"
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      security_group: "{{ec2_group.group_id}}"
      wait: true
      region: "{{ region }}"
      user_data: "{{ lookup('file', 't.sh') }}"
      network:
          assing_public_ip: true
    register: ec2
       
  - name: 'Add all instance public IPs to host group'
    add_host: hostname={{ item.instance_id }} groups=ec2hosts
    loop: "{{ ec2.instances }}"
        
  - name: 'Sainda de informações da instancia'
    debug:
      var:
        ec2
        eip
